### ISSUE TITLE
Broken image badges at the top of the README

### ISSUE THREAD

**Issue by mbrukman** [encord-team/encord-notebooks#22]
The badges at the top of the [`README.md`](https://github.com/encord-team/encord-notebooks/blob/9d7723e163899c7b36df4fe8bef0048855662b91/README.md?plain=1#L12-L28) currently render as follows:

> <div align="center" dir="auto">
> 
> <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/1a088dbe61584d1b213517c05e313c765ca127ce21118626b2d0db0b8f573235/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f6c6963656e73652f656e636f72642d7465616d2f656e636f72642d616374697665"><img src="https://camo.githubusercontent.com/1a088dbe61584d1b213517c05e313c765ca127ce21118626b2d0db0b8f573235/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f6c6963656e73652f656e636f72642d7465616d2f656e636f72642d616374697665" alt="Licence" data-canonical-src="https://img.shields.io/github/license/encord-team/encord-active" style="max-width: 100%;"></a>
> <a href="https://www.piwheels.org/project/encord-active/" rel="nofollow"><img src="https://camo.githubusercontent.com/ad0f13bbb94beadb953a46e51cee0db17ade62e4deb8c306e36a7addfa69d18f/68747470733a2f2f696d672e736869656c64732e696f2f707970692f762f656e636f72642d616374697665" alt="PyPi project" data-canonical-src="https://img.shields.io/pypi/v/encord-active" style="max-width: 100%;"></a>
> <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/890ceffab6602e1a6ecac875e179b3984708f98b0a91293e6c632752d11bad7e/68747470733a2f2f696d672e736869656c64732e696f2f707970692f707976657273696f6e732f656e636f72642d616374697665"><img src="https://camo.githubusercontent.com/890ceffab6602e1a6ecac875e179b3984708f98b0a91293e6c632752d11bad7e/68747470733a2f2f696d672e736869656c64732e696f2f707970692f707976657273696f6e732f656e636f72642d616374697665" alt="PyPi version" data-canonical-src="https://img.shields.io/pypi/pyversions/encord-active" style="max-width: 100%;"></a>
> 
> <a href="https://docs.encord.com/docs/active-overview" rel="nofollow"><img src="https://camo.githubusercontent.com/457447b616a4e5aecccd5351fa78d41ce828901e395b935ad2a94d94db75e5d0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f646f63732d6f6e6c696e652d626c7565" alt="docs" data-canonical-src="https://img.shields.io/badge/docs-online-blue" style="max-width: 100%;"></a>
> <a href="https://join.slack.com/t/encordactive/shared_invite/zt-1hc2vqur9-Fzj1EEAHoqu91sZ0CX0A7Q" target="_blank" style="text-decoration:none">
> <img alt="Join us on Slack" src="https://img.shields.io/badge/Join_Our_Community-4A154B?label=&logo=slack&logoColor=white">
> </a>
> <a href="https://github.com/encord-team/encord-notebooks" rel="nofollow"><img src="https://badges.aleen42.com/src/github.svg" alt="&quot;Encord Notebooks;" data-canonical-src="https://badges.aleen42.com/src/github.svg" style="max-width: 100%;"></a>
> 
> </p>
> <p dir="auto">
> <a href="https://twitter.com/encord_team" rel="nofollow"><img src="https://camo.githubusercontent.com/c7ea37e4d1f0c2e900069152f5990d3bcef4a69c97dede26f08d588958410bd8/68747470733a2f2f696d672e736869656c64732e696f2f747769747465722f666f6c6c6f772f656e636f72645f7465616d3f6c6162656c3d253430656e636f72645f7465616d267374796c653d736f6369616c" alt="Twitter Follow" data-canonical-src="https://img.shields.io/twitter/follow/encord_team?label=%40encord_team&amp;style=social" style="max-width: 100%;"></a></p>
> </div>

There are a lot of references to https://camo.githubusercontent.com/ which should probably point to https://shields.io/ or similar services which have stable URLs. The few badges that do (e.g., Slack) are rendering fine.

**Comment by frederik-encord** [comment]
Thanks for pointing this out.

**Comment by stephen-encord** [comment]
@mbrukman, thanks a ton for pointing it out and sharing your recommendation. We have resolved this issue.
